In [6]:
import pandas as pd

ds = pd.read_csv("Movie Interests.csv")
ds.head()

Age  Gender   Interest
0    8       1  Animation
1   11       1  Animation
2   12       1  Animation
3   16       1     Action
4   18       1     Action

In [2]:
import numpy as np
from time import process_time

List time

In [24]:
list_process = [i for i in range(10000000)]

start_time = process_time()

list_process = [i+5 for i in list_process]

end_time = process_time()

print(end_time - start_time)

0.59375


NumPy array

In [25]:
numpy_array = np.array([i for i in range(10000000)])

start_time = process_time()

numpy_array =+ 1

end_time = process_time()

print(end_time - start_time)

0.0


In [30]:
a = np.array([1,2,3,4,5])
print(a)
type(a)
a.shape

[1 2 3 4 5]


(5,)

In [6]:
b = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(b)
type(b)
b.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

Initial Place Holders

In [11]:
x = np.zeros((3,3))
print(x)

y = np.full((2,3),5)
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5 5 5]
 [5 5 5]]


In [12]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
x = np.random.randint(10,100,(2,4))
print(x)
y =np.arange(10,30,5)
print(y)

[[51 52 52 81]
 [67 92 40 71]]
[10 15 20 25]


In [18]:
l = [1,2,3,4,5]
np_array = np.asarray(l)
print(np_array)

[1 2 3 4 5]


In [25]:
a = np.random.randint(10,100,(2,3))
b = np.random.randint(10,100,(2,3))

print(a)
print(b)

[[49 20 81]
 [41 13 55]]
[[63 59 96]
 [35 15 75]]


In [28]:
c =a+b
print(c.T)

[[112  76]
 [ 79  28]
 [177 130]]


In [35]:
print(c.reshape(2,3))

[[112  79 177]
 [ 76  28 130]]
